{
  "Header": {
    "Original": "CVE-2024-3651 (A vulnerability was identified in the kjd/idna library, specifically w ...)",
    "ID": "CVE-2024-3651",
    "Description": "(A vulnerability was identified in the kjd/idna library, specifically w ...)"
  },
  "Annotations": [
    {
      "Original": "{DLA-3811-1}",
      "Type": "xref",
      "Bugs": [
        "DLA-3811-1"
      ]
    },
    {
      "Original": "- python-idna 3.6-2.1 (bug #1069127)",
      "Type": "package",
      "Package": "python-idna",
      "Kind": "fixed",
      "Version": "3.6-2.1",
      "BugNo": 1069127
    },
    {
      "Original": "[bookworm] - python-idna 3.3-1+deb12u1",
      "Type": "package",
      "Release": "bookworm",
      "Package": "python-idna",
      "Kind": "fixed",
      "Version": "3.3-1+deb12u1"
    },
    {
      "Original": "[bullseye] - python-idna 2.10-1+deb11u1",
      "Type": "package",
      "Release": "bullseye",
      "Package": "python-idna",
      "Kind": "fixed",
      "Version": "2.10-1+deb11u1"
    },
    {
      "Original": "NOTE: https://github.com/kjd/idna/security/advisories/GHSA-jjg7-2v4v-x38h",
      "Type": "NOTE",
      "Description": "https://github.com/kjd/idna/security/advisories/GHSA-jjg7-2v4v-x38h"
    },
    {
      "Original": "NOTE: https://bugzilla.redhat.com/show_bug.cgi?id=2274779",
      "Type": "NOTE",
      "Description": "https://bugzilla.redhat.com/show_bug.cgi?id=2274779"
    },
    {
      "Original": "NOTE: Fixed by: https://github.com/kjd/idna/commit/5beb28b9dd77912c0dd656d8b0fdba3eb80222e7 (v3.7)",
      "Type": "NOTE",
      "Description": "Fixed by: https://github.com/kjd/idna/commit/5beb28b9dd77912c0dd656d8b0fdba3eb80222e7 (v3.7)"
    }
  ]
}