{
  "Header": {
    "Original": "CVE-2024-45230 (An issue was discovered in Django 5.1 before 5.1.1, 5.0 before 5.0.9,  ...)",
    "ID": "CVE-2024-45230",
    "Description": "(An issue was discovered in Django 5.1 before 5.1.1, 5.0 before 5.0.9,  ...)"
  },
  "Annotations": [
    {
      "Original": "- python-django 3:4.2.16-1",
      "Type": "package",
      "Package": "python-django",
      "Kind": "fixed",
      "Version": "3:4.2.16-1"
    },
    {
      "Original": "[bookworm] - python-django \u003cno-dsa\u003e (Minor issue)",
      "Type": "package",
      "Release": "bookworm",
      "Package": "python-django",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "[bullseye] - python-django \u003cpostponed\u003e (Minor issue; can be fixed in next update)",
      "Type": "package",
      "Release": "bullseye",
      "Package": "python-django",
      "Kind": "postponed",
      "Description": "Minor issue; can be fixed in next update"
    },
    {
      "Original": "NOTE: https://www.djangoproject.com/weblog/2024/sep/03/security-releases/",
      "Type": "NOTE",
      "Description": "https://www.djangoproject.com/weblog/2024/sep/03/security-releases/"
    },
    {
      "Original": "NOTE: https://github.com/django/django/commit/d147a8ebbdf28c17cafbbe2884f0bc57e2bf82e2 (4.2.16)",
      "Type": "NOTE",
      "Description": "https://github.com/django/django/commit/d147a8ebbdf28c17cafbbe2884f0bc57e2bf82e2 (4.2.16)"
    }
  ]
}