{
  "Header": {
    "Original": "CVE-2024-39614 (An issue was discovered in Django 5.0 before 5.0.7 and 4.2 before 4.2. ...)",
    "ID": "CVE-2024-39614",
    "Description": "(An issue was discovered in Django 5.0 before 5.0.7 and 4.2 before 4.2. ...)"
  },
  "Annotations": [
    {
      "Original": "- python-django 3:4.2.14-1 (bug #1076069)",
      "Type": "package",
      "Package": "python-django",
      "Kind": "fixed",
      "Version": "3:4.2.14-1",
      "BugNo": 1076069
    },
    {
      "Original": "[bookworm] - python-django \u003cno-dsa\u003e (Minor issue)",
      "Type": "package",
      "Release": "bookworm",
      "Package": "python-django",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "[bullseye] - python-django \u003cpostponed\u003e (Minor issue)",
      "Type": "package",
      "Release": "bullseye",
      "Package": "python-django",
      "Kind": "postponed",
      "Description": "Minor issue"
    },
    {
      "Original": "NOTE: https://www.djangoproject.com/weblog/2024/jul/09/security-releases/",
      "Type": "NOTE",
      "Description": "https://www.djangoproject.com/weblog/2024/jul/09/security-releases/"
    },
    {
      "Original": "NOTE: https://github.com/django/django/commit/17358fb35fb7217423d4c4877ccb6d1a3a40b1c3 (4.2.14)",
      "Type": "NOTE",
      "Description": "https://github.com/django/django/commit/17358fb35fb7217423d4c4877ccb6d1a3a40b1c3 (4.2.14)"
    },
    {
      "Original": "NOTE: Relates to CVE-2023-23969 fix",
      "Type": "NOTE",
      "Description": "Relates to CVE-2023-23969 fix"
    }
  ]
}