{
  "Header": {
    "Original": "CVE-2024-41990 (An issue was discovered in Django 5.0 before 5.0.8 and 4.2 before 4.2. ...)",
    "ID": "CVE-2024-41990",
    "Description": "(An issue was discovered in Django 5.0 before 5.0.8 and 4.2 before 4.2. ...)"
  },
  "Annotations": [
    {
      "Original": "- python-django 3:4.2.15-1 (bug #1078074)",
      "Type": "package",
      "Package": "python-django",
      "Kind": "fixed",
      "Version": "3:4.2.15-1",
      "BugNo": 1078074
    },
    {
      "Original": "[bookworm] - python-django \u003cno-dsa\u003e (Minor issue; intrusive to backport)",
      "Type": "package",
      "Release": "bookworm",
      "Package": "python-django",
      "Kind": "no-dsa",
      "Description": "Minor issue; intrusive to backport"
    },
    {
      "Original": "[bullseye] - python-django \u003cpostponed\u003e (Minor issue)",
      "Type": "package",
      "Release": "bullseye",
      "Package": "python-django",
      "Kind": "postponed",
      "Description": "Minor issue"
    },
    {
      "Original": "NOTE: https://www.djangoproject.com/weblog/2024/aug/06/security-releases/",
      "Type": "NOTE",
      "Description": "https://www.djangoproject.com/weblog/2024/aug/06/security-releases/"
    },
    {
      "Original": "NOTE: https://github.com/django/django/commit/d0a82e26a74940bf0c78204933c3bdd6a283eb88/ (4.2.15)",
      "Type": "NOTE",
      "Description": "https://github.com/django/django/commit/d0a82e26a74940bf0c78204933c3bdd6a283eb88/ (4.2.15)"
    }
  ]
}