{
  "Header": {
    "Original": "CVE-2020-29651 (A denial of service via regular expression in the py.path.svnwc compon ...)",
    "ID": "CVE-2020-29651",
    "Description": "(A denial of service via regular expression in the py.path.svnwc compon ...)"
  },
  "Annotations": [
    {
      "Original": "{DLA-3966-1}",
      "Type": "xref",
      "Bugs": [
        "DLA-3966-1"
      ]
    },
    {
      "Original": "- python-py 1.10.0-1",
      "Type": "package",
      "Package": "python-py",
      "Kind": "fixed",
      "Version": "1.10.0-1"
    },
    {
      "Original": "[buster] - python-py \u003cno-dsa\u003e (Minor issue)",
      "Type": "package",
      "Release": "buster",
      "Package": "python-py",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "[stretch] - python-py \u003cpostponed\u003e (Minor issue)",
      "Type": "package",
      "Release": "stretch",
      "Package": "python-py",
      "Kind": "postponed",
      "Description": "Minor issue"
    },
    {
      "Original": "- pypy \u003cunfixed\u003e (unimportant)",
      "Type": "package",
      "Package": "pypy",
      "Kind": "unfixed",
      "Severity": "unimportant"
    },
    {
      "Original": "- pypy3 \u003cunfixed\u003e (unimportant)",
      "Type": "package",
      "Package": "pypy3",
      "Kind": "unfixed",
      "Severity": "unimportant"
    },
    {
      "Original": "NOTE: https://github.com/pytest-dev/py/issues/256",
      "Type": "NOTE",
      "Description": "https://github.com/pytest-dev/py/issues/256"
    },
    {
      "Original": "NOTE: https://github.com/pytest-dev/py/pull/257",
      "Type": "NOTE",
      "Description": "https://github.com/pytest-dev/py/pull/257"
    },
    {
      "Original": "NOTE: https://github.com/pytest-dev/py/commit/4a9017dc6199d2a564b6e4b0aa39d6d8870e4144",
      "Type": "NOTE",
      "Description": "https://github.com/pytest-dev/py/commit/4a9017dc6199d2a564b6e4b0aa39d6d8870e4144"
    }
  ]
}