{
  "Header": {
    "Original": "CVE-2020-25658 (It was found that python-rsa is vulnerable to Bleichenbacher timing at ...)",
    "ID": "CVE-2020-25658",
    "Description": "(It was found that python-rsa is vulnerable to Bleichenbacher timing at ...)"
  },
  "Annotations": [
    {
      "Original": "- python-rsa \u003cunfixed\u003e (unimportant; bug #974685)",
      "Type": "package",
      "Package": "python-rsa",
      "Kind": "unfixed",
      "Severity": "unimportant",
      "BugNo": 974685
    },
    {
      "Original": "NOTE: https://github.com/sybrenstuvel/python-rsa/issues/165",
      "Type": "NOTE",
      "Description": "https://github.com/sybrenstuvel/python-rsa/issues/165"
    },
    {
      "Original": "NOTE: Presumed fix upstream in 4.7 does not address the issue:",
      "Type": "NOTE",
      "Description": "Presumed fix upstream in 4.7 does not address the issue:"
    },
    {
      "Original": "NOTE: https://github.com/sybrenstuvel/python-rsa/issues/165#issuecomment-727580521",
      "Type": "NOTE",
      "Description": "https://github.com/sybrenstuvel/python-rsa/issues/165#issuecomment-727580521"
    },
    {
      "Original": "NOTE: The library doesn't intend to guard against this: https://github.com/sybrenstuvel/python-rsa/issues/165#issuecomment-1603113867",
      "Type": "NOTE",
      "Description": "The library doesn't intend to guard against this: https://github.com/sybrenstuvel/python-rsa/issues/165#issuecomment-1603113867"
    }
  ]
}