{
  "Header": {
    "Original": "CVE-2025-46421 (A flaw was found in libsoup. When libsoup clients encounter an HTTP re ...)",
    "ID": "CVE-2025-46421",
    "Description": "(A flaw was found in libsoup. When libsoup clients encounter an HTTP re ...)"
  },
  "Annotations": [
    {
      "Original": "- libsoup3 3.6.5-1",
      "Type": "package",
      "Package": "libsoup3",
      "Kind": "fixed",
      "Version": "3.6.5-1"
    },
    {
      "Original": "- libsoup2.4 \u003cunfixed\u003e",
      "Type": "package",
      "Package": "libsoup2.4",
      "Kind": "unfixed"
    },
    {
      "Original": "NOTE: https://gitlab.gnome.org/GNOME/libsoup/-/issues/439",
      "Type": "NOTE",
      "Description": "https://gitlab.gnome.org/GNOME/libsoup/-/issues/439"
    },
    {
      "Original": "NOTE: https://gitlab.gnome.org/GNOME/libsoup/-/merge_requests/436",
      "Type": "NOTE",
      "Description": "https://gitlab.gnome.org/GNOME/libsoup/-/merge_requests/436"
    },
    {
      "Original": "NOTE: Fixed by: https://gitlab.gnome.org/GNOME/libsoup/-/commit/3e5c26415811f19e7737238bb23305ffaf96f66b (3.6.5)",
      "Type": "NOTE",
      "Description": "Fixed by: https://gitlab.gnome.org/GNOME/libsoup/-/commit/3e5c26415811f19e7737238bb23305ffaf96f66b (3.6.5)"
    }
  ]
}